### ISSUE TITLE
New website "oueiss"

### ISSUE THREAD

**Issue by omelki** [omelki/Oueiss#1]
I need you to set and host the website then upload (under construction page) the picture is attached.

And I need you to create the following email: omelki@oueiss.com

Thanks 

Coming Soon Image in here : https://cloud.githubusercontent.com/assets/7605683/7679015/69a9832e-fd61-11e4-90c7-4ff711209d96.jpg

**Comment by omelki** [comment]
Godaddy Credentials:

Username: 91338209
Password: Omar.melki10

**Comment by FadiZahhar** [comment]
this is a public repository, I will delete the credentials above or everyone notice them.

also, http://oueiss.herokuapp.com/ was created successfully to heroku, now I'm pointing the dns

**Comment by FadiZahhar** [comment]
http://www.oueiss.com/

this issue is closed.
