### ISSUE TITLE
Gmail account to be omelki@oueiss.com

### ISSUE THREAD

**Issue by omelki** [omelki/Oueiss#2]
And I need you to create the following email: omelki@oueiss.com

**Comment by FadiZahhar** [comment]
ok I took the godaddy credentials, from here, and put them somewhere safe. 

tonight I will work on this issue.

public repository , anybody could enter and see the username and password, private repositories is private that no one can see what we are doing.

**Comment by FadiZahhar** [comment]
all mx records of google was set successfully following this document.

http://kb.mediatemple.net/questions/95/How+do+I+point+my+mail+to+Google+Apps%3F

you need to register a yearly professional account for  50$ or 5 $ per month to have all the office google apps including professional email @yourdomain.com to set up as many emails and go.
follow this url and buy the account once done give me the credentials to continue and create your email.
http://mediatemple.net/services/googleapps/

regards,

**Comment by FadiZahhar** [comment]
in case they didn't reply , give me your gmail account user name and password to follow this issue with them.

**Comment by FadiZahhar** [comment]
all available apps was added to this domain , from docs, excell, power point, site creator , calendar and drive.
Enjoy.
